[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# You can add more dependencies as needed
# For example, for a more robust web server:
# actix-web = "4.3.1"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0" 